In [1]:
import numpy as np
x = [2,5,7,6,3,4,6]
w = np.eye(10)[x]
print(w)

print(w.shape[0])
print(w.shape[1])

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
7
10


In [14]:
y = [2,5,7,6,3,4,6]
y_one_hot = np.eye(8)[y]
print(y_one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [ ]:
tt = np.exp(x) / np.exp(x).sum(-1, keepdims=True)
tt

In [ ]:
tt.sum()

In [ ]:
tt.argmax()

In [ ]:
import pandas as pd

train_df = pd.read_csv('./data/train.tsv', sep='\t')
X_data, y_data = train_df["Phrase"].values, train_df["Sentiment"].values

In [ ]:
X_data = X_data[:100]

In [ ]:
import numpy as np

class BagofWords:
    def __init__(self, do_lower_case=False):
        self.vocab = {}
        self.do_lower_case = do_lower_case

    def fit_transform(self, sent_list):
        for sent in sent_list:   #每一个句子
            if self.do_lower_case:  #是否要转化为小写字母
                sent = sent.lower()
            words = sent.strip().split(" ")
            for word in words:
                if word not in self.vocab:
                    self.vocab[word] = len(self.vocab)
        vocab_size = len(self.vocab)
        bag_of_words_features = np.zeros((len(sent_list), vocab_size))
        for idx, sent in enumerate(sent_list):
            if self.do_lower_case:
                sent = sent.lower()
            words = sent.strip().split(" ")
            for word in words:
                bag_of_words_features[idx][self.vocab[word]] += 1
        return bag_of_words_features

In [ ]:
for sent in X_data:   #每一个句子
    words = sent.strip().split(" ")
    print(words)